# https://docs.netlify.com/configure-builds/file-based-configuration/

# All deploys from the Production branch
[context.production]
  command = "npm run build:prod"

[context.production.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://inspirebreda.nl"

# All deploys that are not from
# a pull/merge request or from the Production branch
[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://development.inspirebreda.nl"

# Environment variables set here
# are available for local development environments
# run using Netlify Dev
[context.dev]
  command = "npm run build"

[context.dev.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://development.inspirebreda.nl"

# More specific branch context
[context.development]
  command = "npm run build"

[context.development.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://development.inspirebreda.nl"

[context.split-test]
  command = "npm run build:prod"

[context.split-test.environment]
  NODE_ENV = "development"
  VITE_BASE_URL = "https://inspirebreda.nl"

# Set configuration overrides for local
# development environments run using Netlify Dev - except
# for environment variables
[dev]
  targetPort = 3000
